from sqlalchemy import Column, Integer, String, Boolean, Float, JSON, ForeignKey, DateTime, Table, Numeric, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.base_class import Base

class InfluencerPlatform(Base):
    __tablename__ = "influencer_platforms"

    id = Column(Integer, primary_key=True, index=True)
    influencer_id = Column(Integer, ForeignKey("influencers.id"), index=True)
    platform_name = Column(String, nullable=False)
    username = Column(String, nullable=False)
    profile_url = Column(String, nullable=False)
    followers = Column(Integer, default=0)
    posts = Column(Integer, default=0)
    engagement_rate = Column(Float, default=0.0)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    influencer = relationship("Influencer", back_populates="platforms")

class InfluencerStats(Base):
    __tablename__ = "influencer_stats"

    id = Column(Integer, primary_key=True, index=True)
    influencer_id = Column(Integer, ForeignKey("influencers.id"), unique=True, index=True)
    followers = Column(Integer, default=0)
    following = Column(Integer, default=0)
    total_posts = Column(Integer, default=0)
    average_likes = Column(Integer, default=0)
    average_comments = Column(Integer, default=0)
    engagement_rate = Column(Float, default=0.0)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    influencer = relationship("Influencer", back_populates="stats", uselist=False)

class Influencer(Base):
    __tablename__ = "influencers"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.user_id"), unique=True, nullable=False)
    bio = Column(Text)
    categories = Column(JSON, default=list)
    platforms = Column(JSON, default=list)
    stats = Column(JSON, default=dict)
    preferred_brands = Column(JSON, default=list)
    preferred_categories = Column(JSON, default=list)
    preferred_price_range = Column(JSON)
    preferred_regions = Column(JSON, default=list)
    content_style = Column(JSON, default=list)
    available_for_collaboration = Column(Boolean, default=True)
    minimum_fee = Column(Numeric(10, 2))
    maximum_fee = Column(Numeric(10, 2))
    preferred_payment_methods = Column(JSON, default=list)
    preferred_delivery_methods = Column(JSON, default=list)
    preferred_communication_methods = Column(JSON, default=list)
    preferred_content_deadline = Column(Integer)
    preferred_content_review = Column(Boolean, default=True)
    preferred_content_guidelines = Column(Text)
    preferred_content_format = Column(JSON, default=list)
    preferred_content_length = Column(JSON)
    preferred_content_schedule = Column(JSON)
    preferred_content_hashtags = Column(JSON, default=list)
    preferred_content_mentions = Column(JSON, default=list)
    preferred_content_links = Column(JSON, default=list)
    preferred_content_images = Column(Integer)
    preferred_content_videos = Column(Integer)
    preferred_content_audios = Column(Integer)
    preferred_content_texts = Column(Integer)
    preferred_content_emojis = Column(Integer)
    preferred_content_filters = Column(JSON, default=list)
    preferred_content_effects = Column(JSON, default=list)
    preferred_content_music = Column(JSON, default=list)
    preferred_content_fonts = Column(JSON, default=list)
    preferred_content_colors = Column(JSON, default=list)
    preferred_content_backgrounds = Column(JSON, default=list)
    preferred_content_props = Column(JSON, default=list)
    preferred_content_locations = Column(JSON, default=list)
    preferred_content_weather = Column(JSON, default=list)
    preferred_content_time = Column(JSON, default=list)
    preferred_content_season = Column(JSON, default=list)
    preferred_content_occasion = Column(JSON, default=list)
    preferred_content_theme = Column(JSON, default=list)
    preferred_content_mood = Column(JSON, default=list)
    preferred_content_tone = Column(JSON, default=list)
    preferred_content_style = Column(JSON, default=list)
    preferred_content_angle = Column(JSON, default=list)
    preferred_content_focus = Column(JSON, default=list)
    preferred_content_composition = Column(JSON, default=list)
    preferred_content_lighting = Column(JSON, default=list)
    preferred_content_shadow = Column(JSON, default=list)
    preferred_content_reflection = Column(JSON, default=list)
    preferred_content_mirror = Column(JSON, default=list)
    preferred_content_window = Column(JSON, default=list)
    preferred_content_door = Column(JSON, default=list)
    preferred_content_wall = Column(JSON, default=list)
    preferred_content_floor = Column(JSON, default=list)
    preferred_content_ceiling = Column(JSON, default=list)
    preferred_content_stairs = Column(JSON, default=list)
    preferred_content_elevator = Column(JSON, default=list)
    preferred_content_escalator = Column(JSON, default=list)
    preferred_content_bench = Column(JSON, default=list)
    preferred_content_chair = Column(JSON, default=list)
    preferred_content_table = Column(JSON, default=list)
    preferred_content_counter = Column(JSON, default=list)
    preferred_content_bar = Column(JSON, default=list)
    preferred_content_sofa = Column(JSON, default=list)
    preferred_content_bed = Column(JSON, default=list)
    preferred_content_cabinet = Column(JSON, default=list)
    preferred_content_shelf = Column(JSON, default=list)
    preferred_content_rack = Column(JSON, default=list)
    preferred_content_hook = Column(JSON, default=list)
    preferred_content_plant = Column(JSON, default=list)
    preferred_content_flower = Column(JSON, default=list)
    preferred_content_tree = Column(JSON, default=list)
    preferred_content_grass = Column(JSON, default=list)
    preferred_content_rock = Column(JSON, default=list)
    preferred_content_sand = Column(JSON, default=list)
    preferred_content_water = Column(JSON, default=list)
    preferred_content_fire = Column(JSON, default=list)
    preferred_content_air = Column(JSON, default=list)
    preferred_content_earth = Column(JSON, default=list)
    preferred_content_metal = Column(JSON, default=list)
    preferred_content_wood = Column(JSON, default=list)
    preferred_content_glass = Column(JSON, default=list)
    preferred_content_plastic = Column(JSON, default=list)
    preferred_content_fabric = Column(JSON, default=list)
    preferred_content_leather = Column(JSON, default=list)
    preferred_content_rubber = Column(JSON, default=list)
    preferred_content_ceramic = Column(JSON, default=list)
    preferred_content_paper = Column(JSON, default=list)
    preferred_content_cardboard = Column(JSON, default=list)
    preferred_content_foam = Column(JSON, default=list)
    preferred_content_sponge = Column(JSON, default=list)
    preferred_content_cotton = Column(JSON, default=list)
    preferred_content_wool = Column(JSON, default=list)
    preferred_content_silk = Column(JSON, default=list)
    preferred_content_linen = Column(JSON, default=list)
    preferred_content_denim = Column(JSON, default=list)
    preferred_content_corduroy = Column(JSON, default=list)
    preferred_content_tweed = Column(JSON, default=list)
    preferred_content_flannel = Column(JSON, default=list)
    preferred_content_velvet = Column(JSON, default=list)
    preferred_content_suede = Column(JSON, default=list)
    preferred_content_fur = Column(JSON, default=list)
    preferred_content_feather = Column(JSON, default=list)
    preferred_content_sequin = Column(JSON, default=list)
    preferred_content_rhinestone = Column(JSON, default=list)
    preferred_content_pearl = Column(JSON, default=list)
    preferred_content_crystal = Column(JSON, default=list)
    preferred_content_diamond = Column(JSON, default=list)
    preferred_content_gold = Column(JSON, default=list)
    preferred_content_silver = Column(JSON, default=list)
    preferred_content_platinum = Column(JSON, default=list)
    preferred_content_bronze = Column(JSON, default=list)
    preferred_content_copper = Column(JSON, default=list)
    preferred_content_brass = Column(JSON, default=list)
    preferred_content_steel = Column(JSON, default=list)
    preferred_content_iron = Column(JSON, default=list)
    preferred_content_aluminum = Column(JSON, default=list)
    preferred_content_titanium = Column(JSON, default=list)
    preferred_content_zinc = Column(JSON, default=list)
    preferred_content_nickel = Column(JSON, default=list)
    preferred_content_chrome = Column(JSON, default=list)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    platforms = relationship("InfluencerPlatform", back_populates="influencer")
    stats = relationship("InfluencerStats", back_populates="influencer")
    user = relationship("User", back_populates="influencer") 